export const SECONDS_PER_MINUTE = 60;
export const BASIS_POINTS_SCALE = 10_000;
export const WAD = 10n ** 18n;

export const DEFAULT_ORACLE_MAX_AGE_SECONDS = 3 * SECONDS_PER_MINUTE;
export const DEFAULT_SETTLEMENT_WINDOW_SECONDS = 5 * SECONDS_PER_MINUTE;
export const DEFAULT_CROSS_CHAIN_EXPIRY_SECONDS = 30 * SECONDS_PER_MINUTE;

export const MAX_AUTOMATED_CAPITAL_MOVE_BPS = 2_500;
export const MAX_AUTOMATED_COLLATERAL_SALE_BPS = 1_000;
export const MAX_ACCEPTED_SLIPPAGE_BPS = 500;
