[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache_path = "cache"
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true
bytecode_hash = "ipfs"
cbor_metadata = true
auto_detect_remappings = false
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "../../packages/config/generated" },
]

[profile.default.fuzz]
runs = 1_000
max_test_rejects = 100_000

[profile.default.invariant]
runs = 256
depth = 128
fail_on_revert = true

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 256, fail_on_revert = true }
